### ISSUE TITLE
Styleguide Tools > Media Queries

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/edition-node-gulp#21]
These dont appear to be output anywhere that I could obviously see with a quick glance.

**Comment by bmuenzenmeyer** [comment]
Per gitter discussion, this is no longer on spec and may become a plugin

**Comment by geoffp** [comment]
It's never worked for us. It tries to analyze source CSS by looking for raw @media, and it fails for us because our media queries are done with fancy SASS mixins. I had the idea that you might be able to get it working again by inspecting the compiled or copied CSS output in the dist/public directory instead, but that has order-of-operations difficulties and I didn't have the time to spend.

**Comment by bmuenzenmeyer** [comment]
closing this as not relevant to edition-node-gulp
