### ISSUE TITLE
Problem with gulpjs/gulp@4.0

### ISSUE THREAD

**Issue by drupalshift** [pattern-lab/edition-node-gulp#55]
I am using Pattern Lab Node `v1.2.3` on `Windows|Linux`, using the `gulp` configuration.
Actually my problem is gulp 4.0 :( , i know all fancy series , parallel , etc functions are cool but it takes so much time for other projects start migrating , it breaks all of my pipelines , i was using semantic-ui and many other stuffs which rely on gulp@3.\* and importing other tasks into my patternlab setup , now i can't update i think for a long period or changing all gulp new functions to polyfills like sequencer in patternlab gulp , is there any solution other than this !?

**Comment by bmuenzenmeyer** [comment]
I understand that adding existing tasks directly to this gulpfile necessitates a syntax conversion, one that I had to undergo myself in order to make this work and realize the benefits of gulp 4. I apologize if this is an integration inconvenience to larger codebases.

If you are motivated to continue, you can view all the commits to this repo here: https://github.com/pattern-lab/edition-node-gulp/commits/master and reference the [commit prior to the conversion](https://github.com/pattern-lab/edition-node-gulp/commit/26945c30fce04e7b6c06ddd0fb3d7ba271f43cd9) to see the old syntax if you prefer. I doubt it would be difficult to take that as a baseline (its only 15 days old at time of this writing) and reapply any future commits to the gulp 3 syntax. I tried to pull a compare against these two points and time, which you can look at here: https://github.com/pattern-lab/edition-node-gulp/compare/26945c30fce04e7b6c06ddd0fb3d7ba271f43cd9...master 

I know this isn't ideal for everyone and I hope it doesn't discourage your use of Pattern Lab Node, but that being said, I understand if my decisions may turn people away or disqualify the project from consideration in the short term. We just finished a workshop with PL/Node and attendees survived alright.

**Comment by drupalshift** [comment]
@bmuenzenmeyer Na man , it's not going to discourage me from using Pattern Lab Node, since saved me a ton of time , i think it's pay back time , I will try to maintain my project until i have time to make migration 

Thanks for help and info on conversion
